/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stas.thermometer.app;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import stas.thermometer.domains.*;
import stas.thermometer.infrastructures.DatabaseConnector;
import stas.thermometer.infrastructures.IniConfigurationReader;
import stas.thermometer.infrastructures.MesureDataMapper;
import stas.thermometer.presentations.ThermometerPresenter;
import stas.thermometer.presentations.ThermometerView;
import stas.thermometer.views.ConsoleThermometerView;
import java.io.*;
import java.lang.Exception;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.*;

public class App {
    private static final Logger LOG = LogManager.getLogger("stas");

    public static void main(String[] args) throws IOException {


        //TODO construire les objets du système
        // Vérifier si l'argument --config-file est fourni
        int configFileIndex = Arrays.asList(args).indexOf("--config-file");
        if (configFileIndex == -1 || configFileIndex == args.length - 1) {
            LOG.error(" missing configuration file argument");
            return;
        }

        String resource = args[configFileIndex + 1];

        try (InputStream resourceStream = App.class.getClassLoader().getResourceAsStream(resource)) {
            if (resourceStream == null) {
                LOG.error(" configuration file not found");
                return;
            }

            try {
                ConfigurationReader configReader = new IniConfigurationReader(resourceStream);
                Thermometer thermometer = configReader.toThermometer();
                String url = configReader.get("bd","url");
                String user = configReader.get("bd","user");
                String mdp = configReader.get("bd","mdp");


                if (thermometer.name() == null || thermometer.name().isEmpty()) {
                    LOG.error("missing required property name");
                    return;
                }

                if (thermometer.temperatureFormat() == null || thermometer.temperatureFormat().isEmpty()) {
                    LOG.error("missing temperature format property");
                    return;
                }

                if (thermometer.datetimeFormat() == null || thermometer.datetimeFormat().isEmpty()) {
                    LOG.error("missing datetime format property");
                    return;
                }


                List<Jalon> jalons = configReader.getJalons("profile");
                List<Jalon> jalonsHumidite = configReader.getJalons("humidity_profile");
                ThermometerView view = new ConsoleThermometerView();
                ThermometerPresenter presenter = new ThermometerPresenter(thermometer, view, null, null); // `null` temporairement pour `sonde`


                Sonde sonde = new Sonde(jalons);
                presenter.setSonde(sonde);


                view.display(presenter.presentName());
                Thermometer thermometerFull = configReader.toThermometer();
                String thermometerName = thermometer.name();

                DatabaseConnector connector = new DatabaseConnector(url, user, mdp);

                MesureDataMapper mesureDataMapper = new MesureDataMapper(connector, presenter);
                TemperatureAlert temperatureAlert = new TemperatureAlert(presenter, mesureDataMapper);
                HumidityAlert humidityAlert = new HumidityAlert(presenter,mesureDataMapper);

                AgregateurConfig config = new AgregateurConfig(jalons, thermometerName, humidityAlert, temperatureAlert);
                Agregateur agregateur = new Agregateur(presenter, config, mesureDataMapper);

                AgregateurConfig aggregatorHumidityConfig = new AgregateurConfig(jalonsHumidite,thermometerName,humidityAlert,temperatureAlert);
                AgregateurHumidity agregateurHumidity = new AgregateurHumidity(presenter, mesureDataMapper, aggregatorHumidityConfig);

                sonde.registerObserver(agregateur);

                SondeHumidity sondeHumidite = new SondeHumidity(jalonsHumidite);
                presenter.setSondeHumidity(sondeHumidite);
                sondeHumidite.registerObserver(agregateurHumidity);

                ScheduledExecutorService scheduledExecutor = Executors.newSingleThreadScheduledExecutor();

                scheduledExecutor.scheduleAtFixedRate(sonde, 0, 100, TimeUnit.MILLISECONDS);
                scheduledExecutor.scheduleAtFixedRate(sondeHumidite, 0, 100, TimeUnit.MILLISECONDS);


                presenter.runMainLoop();
                scheduledExecutor.shutdown();
                System.exit(0);


            } catch (FileNotFoundException e) {
                LOG.error(" configuration file not found in resources");
            } catch (Exception e) {
                LOG.error("Error: " + e.getMessage());
            }


        }

    }
    }




